Feature/sp 290 create category page
xtech-guru/hubert pull request #18
Opened 2021-03-04 12:10 UTC by Gatreek92

2021-03-04 12:10 UTC, bouthouri commented
Task linked: [SP-290 Category page](https://app.clickup.com/t/2427294/SP-290)

2021-03-15 12:59 UTC, fakhergh requested changes

2021-03-15 12:59 UTC, fakhergh commented on src/components/ArticlePreview/ArticlePreview.js
> +  a:hover {
@Gatreek92 this style can be placed inside a style, e.g:
`a {
....
:hover{
...
}
}`

2021-03-15 12:59 UTC, fakhergh commented on src/components/ArticleContent/ArticleContent.js
> +          <Link to={window.location.href}>{title}</Link>
@Gatreek92 no need to use link here to redirect to the same page. we can treat with this element only as a title.

2021-03-15 12:59 UTC, fakhergh commented on src/components/Footer/Footer.js
> +                  <Link href="https://www.pinterest.de/sorpetaler/hubert-magazin-f%C3%BCr-holzkultur/">
@Gatreek92 should use to property instead of href when using Link component.

2021-03-15 15:27 UTC, Gatreek92 commented on src/components/ArticleContent/ArticleContent.js
> +          <Link to={window.location.href}>{title}</Link>
@fakhergh on the live website its a link

2021-03-16 08:45 UTC, bouthouri approved these changes

2021-03-16 08:46 UTC, merged