SP-289 - Newsletter widget
xtech-guru/hubert pull request #20
Opened 2021-03-10 13:02 UTC by fakhergh

2021-03-10 13:02 UTC, bouthouri commented
Task linked: [SP-289 Newsletter widget](https://app.clickup.com/t/2427294/SP-289)

2021-03-15 09:00 UTC, Gatreek92 requested changes

2021-03-15 09:00 UTC, Gatreek92 commented on src/components/NewsletterPopup/NewsletterPopup.js
> +    props.isClosed ? "-255px" : props.isCollapsed ? "-177px" : "0"};
@fakhergh there still an empty white space in the bottom of the popup when its collapsed

2021-03-15 11:38 UTC, Gatreek92 approved these changes

2021-07-29 17:59 UTC, bouthouri approved these changes

2021-07-29 17:59 UTC, merged