SP-341 - Article suggestion component
xtech-guru/hubert pull request #29
Opened 2021-03-18 11:24 UTC by fakhergh

2021-03-18 11:25 UTC, bouthouri commented
Task linked: [SP-341 Article Suggestion component](https://app.clickup.com/t/2427294/SP-341)

2021-03-18 18:03 UTC, Gatreek92 approved these changes

2021-03-18 18:48 UTC, bouthouri requested changes

2021-03-18 18:48 UTC, bouthouri commented on src/components/ArticleContent/ArticleContent.js
> +            <CrossLinkArticle content={node.content[0].value} link={link} />
Why are we using CrossLinkArticle inside the rich text?
This should be at the bottom of the article and that's it.

2021-03-19 07:56 UTC, bouthouri approved these changes

2021-03-19 07:56 UTC, merged