Bugfix/sp 525 fix author section design in mobile screen
xtech-guru/hubert pull request #87
Opened 2021-08-10 07:56 UTC by BahriRanim

2021-08-11 08:42 UTC, bouthouri requested changes
You did not optimize the CSS as I told you and I can see !important also.
Fix this and let me know.

2021-08-11 08:42 UTC, bouthouri commented on src/components/AuthorBlock/AuthorBlock.module.scss
>      display: flex !important;
you don't need this

2021-08-11 08:47 UTC, BahriRanim commented on src/components/AuthorBlock/AuthorBlock.module.scss
>      display: flex !important;
Done

2021-08-11 14:50 UTC, bouthouri approved these changes

2021-08-11 14:50 UTC, merged

2021-08-12 22:36 UTC, bouthouri commented
Task linked: [SP-525 Fix author section design in mobile screen](https://app.clickup.com/t/2427294/SP-525)