Feature/sp 283 article page
xtech-guru/hubert pull request #9
Opened 2021-02-24 09:30 UTC by Gatreek92

2021-02-24 09:33 UTC, bouthouri commented on src/pages/article.js
> +const ArticleComments = () => {
There will be no comment for the moment the client needs to validate this first.
So we should comment this until we have the green light.

2021-02-24 10:49 UTC, bouthouri requested changes
Gatsby is going to generate an article page for every article.
The article page is going to be used as a template so please change it from an actual page to a template.
Inside template folder.

2021-02-26 06:10 UTC, bouthouri requested changes
Comment rating related code until we have a client confirmation
Extract the author block into a separate component
Use mocked data in components, not hardcoded data

2021-02-28 06:01 UTC, bouthouri commented
Task linked: [SP-283 Article page](https://app.clickup.com/t/2427294/SP-283)

2021-03-01 14:58 UTC, fakhergh commented on src/components/ArticlePreview/ArticlePreview.js
> +const ImageContainer = styled.div`
@Gatreek92 should have the postfix `Wrapper` for naming convention as Oussama said before.

2021-03-01 14:58 UTC, fakhergh commented on src/components/ArticlePreview/ArticlePreview.js
> +const ArticlePreviewContainer = styled.article`
@Gatreek92 should have the postfix Wrapper for naming convention as Oussama said before.

2021-03-01 14:58 UTC, fakhergh commented on src/components/Posts/Posts.js
>  import Masonry from "react-masonry-component"
@Gatreek92 can you please add a new line between node modules and local imports?

2021-03-01 14:58 UTC, fakhergh commented on src/templates/ArticleTemplate.js
> +import { Layout, ArticleContent, RelatedPosts } from "../components"
@Gatreek92 newline please between imports.

2021-03-02 09:11 UTC, merged